version: '3'

services:
  users-ms:
    build: ./
    volumes:
      - ./src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3003
      - DATABASE_URL=postgresql://postgres:123456@users-db:5432/usersdb?schema=public
      - NATS_SERVERS=nats://nats-server:4222
    networks:
      - app_network

  users-db:
    container_name: users_database
    image: postgres:latest
    restart: always
    volumes:
      - ./users-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=usersdb
    networks:
      - app_network

networks:
  app_network:
    external: true
